### ISSUE TITLE
Where I can find testnet Factom Wallet

### ISSUE THREAD

**Issue by hasanaliqureshi** [FactomProject/enterprise-wallet#27]
I want to test factom by using testnet wallet. Can you please tell me where I can find testnet wallet?
I am trying to install factomd on linux but its a very cumbersome process.

**Comment by carryforward** [comment]
Hi Hasan:

Factom is a little different than other projects.  To do experimentation and testing, you can start up your own local factomd node, which serves a testnet.  When you run the wallet, it gets the test transactions, balances, etc.  

Is there a problem building factomd or building enterprise wallet?  

Are you using a debian or fedora based version of Linux?  if it is debian based, you can use the .deb files.  for RPM based, we only have the ability to install from source.
https://github.com/FactomProject/FactomDocs/blob/master/installFromSourceDirections.md#install-factom
https://github.com/FactomProject/distribution#factom-command-line-interface-programs

To test the enterprise wallet, you need factomd installed.

start factomd like this:
`factomd -network=LOCAL`

after installing enterprise wallet (the command go get `github.com/FactomProject/enterprise-wallet` won't work right due to dependencies.  the glide installed method above works if you want to build the wallet from source.)  the dist version has pre-built binaries that might be all you need.
- start enterprise-wallet from the command line
- open http://localhost:8091/Settings
- change Custom Factomd Location to localhost:8088
- click restore seed, and use the word "yellow" for all 12 words.
- go to address book and click new address.  select "random new factoid address" give the nickname yellow1 then add to address book
- go to transactions tab and the address FA22de5NSG2FA2HmMaD4h8qSAZAJyztmmnwgLPghCQKoSekwYYct should read 20000 fct


let me know if this gets you what you need.

**Comment by hasanaliqureshi** [comment]
Thank you.
